[package]
name = "strprox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bitvec = "1"
#ndarray = "0.15"
priority-queue = "1"
#num = "0.4"
serde = { version = "1", optional = true }

[features]
serde = ["dep:serde"]