[package]
name = "strprox"
version = "0.1.0"
edition = "2021"

[dependencies]
#bitvec = "1"
#priority-queue = "1"
#num = "0.4"
#serde = { version = "1", optional = true }

[dev-dependencies]
rand = "0.8"

[features]

[profile.test]
opt-level = 3
